version: "3"
services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
     - "5672:5672"
     - "15672:15672"
  mssql:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=TransactionBank2023Masstransit!"
    ports:
      - "1433:1433"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"